//! Resolves the toolchain-dependent C99 integer types without bindgen.
//!
//! `src/probe.c` is run through the target's C preprocessor (via the `cc`
//! crate). Its `#if` ladders classify each type's width by comparing `*_MAX`
//! macros, leaving one `RUST_STDINT <ctype> <rust-type>` marker per type. We
//! parse those markers and emit the corresponding Rust type aliases into
//! `$OUT_DIR/types.rs`, which `lib.rs` includes.

use std::env;
use std::path::PathBuf;

/// Types the probe is expected to resolve. Used to fail loudly if the
/// preprocessor output is incomplete (e.g. a header that omits a macro).
const EXPECTED: &[&str] = &[
    "int_fast8_t",
    "int_fast16_t",
    "int_fast32_t",
    "int_fast64_t",
    "uint_fast8_t",
    "uint_fast16_t",
    "uint_fast32_t",
    "uint_fast64_t",
    "intmax_t",
    "uintmax_t",
];

fn main() {
    println!("cargo:rerun-if-changed=src/probe.c");
    println!("cargo:rerun-if-changed=build.rs");

    // Preprocess only; this never produces an object file. `expand()` invokes
    // the configured target compiler with `-E`, so it cross-compiles correctly.
    let expanded = cc::Build::new().file("src/probe.c").expand();
    let expanded = String::from_utf8(expanded).expect("preprocessor output was not UTF-8");

    let mut generated = String::from("// @generated by build.rs from src/probe.c\n");
    let mut seen = Vec::new();

    for line in expanded.lines() {
        let Some(rest) = line.trim().strip_prefix("RUST_STDINT ") else {
            continue;
        };
        let mut parts = rest.split_whitespace();
        let ctype = parts
            .next()
            .unwrap_or_else(|| panic!("malformed probe marker: {line:?}"));
        let rtype = parts
            .next()
            .unwrap_or_else(|| panic!("malformed probe marker: {line:?}"));
        assert!(
            !seen.iter().any(|c| c == ctype),
            "duplicate probe marker for `{ctype}`; preprocessor output was:\n{expanded}"
        );
        generated.push_str(&format!("pub type {ctype} = {rtype};\n"));
        seen.push(ctype.to_string());
    }

    for expected in EXPECTED {
        assert!(
            seen.iter().any(|c| c == expected),
            "probe did not resolve `{expected}`; preprocessor output was:\n{expanded}"
        );
    }

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("types.rs");
    std::fs::write(&out_path, generated).expect("failed to write generated types");
}
